version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csai
    image: csai
    ports:
      - "2223:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ad_main.html:/usr/share/nginx/html/ad_main.html  
      - ./index.html:/usr/share/nginx/html/index.html  
      - ./CSAIgifandpic.html:/usr/share/nginx/html/CSAIgifandpic.html
      - ./vid:/usr/share/nginx/html/vid  
      - ./js:/usr/share/nginx/html/js
    restart: always
    networks:
      - csai

networks:
  csai:
    driver: bridge
